### ISSUE TITLE
Unification of PR templates

### ISSUE THREAD

**Issue by tmspzz** [wireapp/.github#6]
This is an RFC regarding the PR template proposed here:

https://github.com/wireapp/.github/blob/c5bec40c07b2b68e4687bf33aed298dc968d0525/.github/pull_request_template.md

What are we trying to fix?

1) Having a unified and automation friendly PR Template.
1) Making sure work is tracked and moves automatically in our boards with minimal developer intervention. 

So far:

- Q: Is the Jira ticket really necessary?
  - A: Yes, it keeps work moving automatically on our boards. Feel free to reuse a PR title or branch if work is related.

- Q: Is the brach format necessary?
  - A: Depends, will have to verify with Jira plugin 
  - A: According to the Jira plugin documentation the PR title or mentioning the ticket in a commit should be enough

**Comment by makingthematrix** [comment]
I would suggest that the requirement for a JIRA ticket should be optional. Sometimes it may happen that we have some code before there's a JIRA ticket or the code is some very specific change that came up as a side-effect of something else, and making a ticket for that would just be a burden and slow things down significantly.

**Comment by typfel** [comment]
Would have been easier to discuss if the template was not already merged and port of this PR.

----

Do we really need this:
```
PR Post Submission Checklist for internal contributors

 Wire's Github Workflow has automatically linked the PR to a JIRA issue
 ```
 
 Wouldn't a "check" fail if this wasn't the case?

**Comment by tmspzz** [comment]
> I would suggest that the requirement for a JIRA ticket should be optional. Sometimes it may happen that we have some code before there's a JIRA ticket or the code is some very specific change that came up as a side-effect of something else, and making a ticket for that would just be a burden and slow things down significantly.


Nope sorry. That's exactly what we're trying to fix.

**Comment by tmspzz** [comment]
> Would have been easier to discuss if the template was not already merged and port of this PR.
> 
> ----
> 
> 
> 
> Do we really need this:
> 
> ```
> 
> PR Post Submission Checklist for internal contributors
> 
> 
> 
>  Wire's Github Workflow has automatically linked the PR to a JIRA issue
> 
>  ```
> 
>  
> 
>  Wouldn't a "check" fail if this wasn't the case?

The file is merged as a base for discussion. 


About the check: I am not sure that GitHub actions can fail PR thus stopping the merge. But they will surface as fails. 

I will check if this particular action fails on error.

**Comment by makingthematrix** [comment]
@tmspzz : What are we trying to fix?

**Comment by Gardosen** [comment]
"contains a reference JIRA issue number like" is a small subset of "answers the question: If merged, this PR will: ... . E.g."
as it is required there will always be a JIRA Ticket part of it.
so "contains a reference JIRA issue number like" is obsolete.

in addition i do not think it makes sense to add the ticket id to the branch name as it could happen that multiple tickets are part of one PR, especially on bigger feature merges. i would there for suggest to stick to making sure the ticket ids are part of the PR Question as this allows a 1:m relation (PR:tickets)

**Comment by tmspzz** [comment]
> "contains a reference JIRA issue number like" is a small subset of "answers the question: If merged, this PR will: ... . E.g."
> 
> as it is required there will always be a JIRA Ticket part of it.
> 
> so "contains a reference JIRA issue number like" is obsolete.
> 
> 
> 
> in addition i do not think it makes sense to add the ticket id to the branch name as it could happen that multiple tickets are part of one PR, especially on bigger feature merges. i would there for suggest to stick to making sure the ticket ids are part of the PR Question as this allows a 1:m relation (PR:tickets)
> 
> 

I have to investigate if having the Jira issue in the branch is required by the jira-GitHub plugging. 

If not then I agree that's an overkill

About the other points, one is about actually having the jira issue in the title, the second one is about the langue style. I don't agree they are subsets of each other.

**Comment by tmspzz** [comment]
> @tmspzz : What are we trying to fix?

1) Having a unified and automation friendly Pr Template.
1) Making sure work is tracked and moves automatically in our boards with minimal developer intervention. 

If a fix is related to a previous PR it's completely fine to reuse the title and the branch from the previous PR if appropriate.

**Comment by Gardosen** [comment]
> > "contains a reference JIRA issue number like" is a small subset of "answers the question: If merged, this PR will: ... . E.g."
> > as it is required there will always be a JIRA Ticket part of it.
> > so "contains a reference JIRA issue number like" is obsolete.
> > in addition i do not think it makes sense to add the ticket id to the branch name as it could happen that multiple tickets are part of one PR, especially on bigger feature merges. i would there for suggest to stick to making sure the ticket ids are part of the PR Question as this allows a 1:m relation (PR:tickets)
> 
> I have to investigate if having the Jira issue in the branch is required by the jira-GitHub plugging.
> 
> If not then I agree that's an overkill
> 
> About the other points, one is about actually having the jira issue in the title, the second one is about the langue style. I don't agree they are subsets of each other.

oh #2 is about the title. then i agree, it should stay as a primary reference. 👍

**Comment by tmspzz** [comment]
Update: The branch format is not necessary for the JIRA plugin to work, it's enough if the PR title or commits contain a ticket id

**Comment by tmspzz** [comment]
@typfel @Gardosen @makingthematrix @Yserz @David-Henner 

I have been using this for about a week and while it's useful I feel that the links are way too verbose so I suggest moving them to the bottom

**Comment by tmspzz** [comment]
Closing and implementing
